apiVersion: v1
kind: ConfigMap
metadata:
  name: central-station-config
  namespace: weather
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.weather.svc.cluster.local:9092"
  APP_TOPIC_INPUT: "weather.telemetry.v1"
  APP_TOPIC_ALERTS: "weather.alerts.rain.v1"
  BITCASK_DATA_PATH: "/data/bitcask"
  PARQUET_DATA_PATH: "/data/parquet"
  ARCHIVER_FLUSH_INTERVAL_MS: "30000"
