spring.application.name=central-station

# Spring Kafka Properties
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Spring Kafka Streams Properties
spring.kafka.streams.application-id=central-station-processor
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde
spring.kafka.streams.properties.spring.json.trusted.packages=*

# Error handling: Log and continue on deserialization errors instead of crashing the stream
spring.kafka.streams.properties.default.deserialization.exception.handler=org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

# Application Specific Properties
app.topic.input=${APP_TOPIC_INPUT:weather.telemetry.v1}
app.topic.alerts=${APP_TOPIC_ALERTS:weather.alerts.rain.v1}
